### ISSUE TITLE
Tiff issue in compile on MacOS10.9

### ISSUE THREAD

**Issue by dgoodwin208** [abria/TeraStitcher#1]
I'm unable to compile on Mac, seeing an issue in reference to tiff3d. I have libtiff-4.0.3 installed via homebrew, but perhaps this is the wrong version?  Seeing _exception specification of overriding function is more lax than base version_

Any ideas? Thanks!

Running `cmake -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release`
Cropped result:
Linking CXX static library ../libs/libimagemanager.a
[ 75%] Built target imagemanager
Scanning dependencies of target ioplugin_tiff3D
[ 76%] Building CXX object iomanager/plugins/tiff3D/CMakeFiles/ioplugin_tiff3D.dir/tiff3D.cpp.o
In file included from /Users/dangoodwin/Downloads/abria-TeraStitcher-7a58718/src/iomanager/plugins/tiff3D/tiff3D.cpp:1:
/Users/dangoodwin/Downloads/abria-TeraStitcher-7a58718/src/3rdparty/libtiff/tiffio.h:67:9: error: unknown
      type name 'size_t'
typedef TIFF_SSIZE_T tmsize_t;
        ^
/Users/dangoodwin/Downloads/abria-TeraStitcher-7a58718/src/build/3rdparty/libtiff/tif_config.h:121:22: note: 
      expanded from macro 'TIFF_SSIZE_T'
# define TIFF_SSIZE_T size_t

```
                 ^
```

In file included from /Users/dangoodwin/Downloads/abria-TeraStitcher-7a58718/src/iomanager/plugins/tiff3D/tiff3D.cpp:2:
In file included from /Users/dangoodwin/Downloads/abria-TeraStitcher-7a58718/src/iomanager/plugins/tiff3D/tiff3D.h:4:
In file included from /Users/dangoodwin/Downloads/abria-TeraStitcher-7a58718/src/iomanager/plugins/tiff3D/../../IOPluginAPI.h:6:
/Users/dangoodwin/Downloads/abria-TeraStitcher-7a58718/src/iomanager/plugins/tiff3D/../../iomanager.config.h:250:24: error: 
      exception specification of overriding function is more lax than base version
                        virtual const char\* what() const {return message.c_str();}
                                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/exception:95:25: note: 
      overridden virtual function is here
    virtual const char\* what() const _NOEXCEPT;
                        ^
In file included from /Users/dangoodwin/Downloads/abria-TeraStitcher-7a58718/src/iomanager/plugins/tiff3D/tiff3D.cpp:2:
In file included from /Users/dangoodwin/Downloads/abria-TeraStitcher-7a58718/src/iomanager/plugins/tiff3D/tiff3D.h:4:
In file included from /Users/dangoodwin/Downloads/abria-TeraStitcher-7a58718/src/iomanager/plugins/tiff3D/../../IOPluginAPI.h:6:
/Users/dangoodwin/Downloads/abria-TeraStitcher-7a58718/src/iomanager/plugins/tiff3D/../../iomanager.config.h:235:8: error: 
      exception specification of overriding function is more lax than base version
        class exception  : public std::exception
              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/exception:94:13: note: 
      overridden virtual function is here
    virtual ~exception() _NOEXCEPT;
            ^
3 errors generated.
make[2]: **\* [iomanager/plugins/tiff3D/CMakeFiles/ioplugin_tiff3D.dir/tiff3D.cpp.o] Error 1
make[1]: **\* [iomanager/plugins/tiff3D/CMakeFiles/ioplugin_tiff3D.dir/all] Error 2
make: **\* [all] Error 2
